import React, { useState, useEffect } from 'react';
import api from '../../services/api';
import { useToast } from '../../hooks/useToast';
import useAuth from '../../hooks/useAuth';
import Badge from '../../components/common/Badge';
import Button from '../../components/common/Button';

const printPayslip = (pay, userName) => {
  const net = pay.netPay || pay.baseSalary;
  const html = `
<!DOCTYPE html>
<html>
<head>
  <title>Payslip – ${pay.month} ${pay.year}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 600px; margin: 40px auto; color: #111; }
    h1 { font-size: 22px; margin-bottom: 4px; }
    .sub { color: #666; font-size: 13px; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; }
    td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 14px; }
    td:last-child { text-align: right; font-weight: 600; }
    .total td { font-size: 16px; font-weight: 700; border-top: 2px solid #111; border-bottom: none; }
    .green { color: #059669; } .red { color: #DC2626; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>Payslip</h1>
  <div class="sub">${pay.month} ${pay.year} &nbsp;·&nbsp; ${userName}</div>
  <table>
    <tr><td>Base Salary</td><td class="green">${pay.baseSalary}</td></tr>
    ${pay.deductions ? `<tr><td>Deductions</td><td class="red">– ${pay.deductions}</td></tr>` : ''}
    <tr class="total"><td>Net Pay</td><td>${net}</td></tr>
  </table>
  <p style="margin-top:32px;font-size:12px;color:#999">Generated by Kodryx Workflow</p>
</body>
</html>`;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
};

const MyPayslips = () => {
  const { user } = useAuth();
  const { addToast } = useToast();
  const [payslips, setPayslips] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/api/payroll/me')
      .then(({ data }) => setPayslips(data || []))
      .catch(() => addToast('Failed to load payslips', 'error'))
      .finally(() => setLoading(false));
  }, []);

  // YTD totals (parse numeric from string like "85000" or "₹85,000")
  const parse = (s) => parseFloat(String(s || '').replace(/[^0-9.]/g, '')) || 0;
  const ytdNet = payslips.reduce((sum, p) => sum + parse(p.netPay || p.baseSalary), 0);
  const ytdDeductions = payslips.reduce((sum, p) => sum + parse(p.deductions), 0);

  return (
    <div className="view active" id="view-my-payslips">
      <div className="section-hdr" style={{ marginBottom: '20px' }}>
        <div>
          <div className="section-title" style={{ fontSize: '18px' }}>My Payslips</div>
          <div className="section-sub">{payslips.length} records</div>
        </div>
      </div>

      {/* YTD summary */}
      {payslips.length > 0 && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px', marginBottom: '20px' }}>
          <div className="stat-card">
            <div className="stat-card-accent" style={{ background: 'var(--success)' }}></div>
            <div className="stat-label"><i className="fas fa-coins" style={{ color: 'var(--success)' }}></i> YTD Earned</div>
            <div className="stat-value" style={{ fontSize: '18px', color: 'var(--success)' }}>
              {ytdNet.toLocaleString()}
            </div>
            <div className="stat-delta delta-neutral">net pay this year</div>
          </div>
          <div className="stat-card">
            <div className="stat-card-accent" style={{ background: 'var(--danger)' }}></div>
            <div className="stat-label"><i className="fas fa-minus-circle" style={{ color: 'var(--danger)' }}></i> YTD Deductions</div>
            <div className="stat-value" style={{ fontSize: '18px', color: 'var(--danger)' }}>
              {ytdDeductions.toLocaleString()}
            </div>
            <div className="stat-delta delta-neutral">total deducted</div>
          </div>
          <div className="stat-card">
            <div className="stat-card-accent" style={{ background: 'var(--brand)' }}></div>
            <div className="stat-label"><i className="fas fa-file-invoice" style={{ color: 'var(--brand)' }}></i> Payslips</div>
            <div className="stat-value" style={{ fontSize: '18px' }}>{payslips.length}</div>
            <div className="stat-delta delta-neutral">on record</div>
          </div>
        </div>
      )}

      <div className="card">
        {loading ? (
          <div style={{ textAlign: 'center', padding: '24px' }}><i className="fas fa-circle-notch fa-spin"></i></div>
        ) : payslips.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text3)' }}>
            <i className="fas fa-file-invoice" style={{ fontSize: '28px', display: 'block', marginBottom: '8px' }}></i>
            No payslips yet
          </div>
        ) : (
          <table className="task-table" style={{ width: '100%' }}>
            <thead>
              <tr>
                <th>Period</th>
                <th>Base Salary</th>
                <th>Deductions</th>
                <th>Net Pay</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {payslips.map(pay => (
                <tr key={pay._id}>
                  <td style={{ fontWeight: 600 }}>{pay.month} {pay.year}</td>
                  <td style={{ fontSize: '13px' }}>{pay.baseSalary}</td>
                  <td style={{ fontSize: '13px', color: 'var(--danger)' }}>
                    {pay.deductions ? `– ${pay.deductions}` : '—'}
                  </td>
                  <td style={{ fontWeight: 700, color: 'var(--success)' }}>
                    {pay.netPay || pay.baseSalary}
                  </td>
                  <td>
                    <Badge variant={pay.status === 'Paid' ? 'success' : 'warning'}>{pay.status}</Badge>
                  </td>
                  <td>
                    <Button variant="ghost" size="sm" icon="download"
                      onClick={() => printPayslip(pay, user?.name || '')}>
                      Download
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
};

export default MyPayslips;
